# Generated by Django 2.1.1 on 2018-10-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='triptype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
    ]
