# Generated by Django 2.1.1 on 2018-10-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripline', '0002_triptype'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripline',
            name='types',
            field=models.ManyToManyField(to='tripline.triptype'),
        ),
    ]
