# Generated by Django 2.1.1 on 2018-10-21 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripline', '0003_tripline_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripline',
            name='producttype',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
