# Generated by Django 2.1.1 on 2018-10-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripline', '0004_tripline_producttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripline',
            name='pageview',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
