# Generated by Django 2.1.1 on 2018-10-22 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tripline', '0006_hotelinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='hotelinfo',
        ),
    ]
