# Generated by Django 2.1.1 on 2018-10-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripline', '0008_hotelinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripline',
            name='hotels',
            field=models.ManyToManyField(to='tripline.hotelinfo'),
        ),
    ]
