# Generated by Django 2.1.1 on 2018-10-18 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tripline', '0003_tripline_types'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='lineevaluate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation', models.CharField(max_length=64)),
                ('trip', models.CharField(max_length=64)),
                ('evaluatetime', models.DateField()),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tripline.tripline')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
