# Generated by Django 2.1.1 on 2018-10-19 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_usericon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usericon',
            name='user',
        ),
        migrations.DeleteModel(
            name='usericon',
        ),
    ]
