# Generated by Django 2.1.1 on 2018-10-19 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_usericon'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='icon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.usericon'),
        ),
    ]
