# Generated by Django 2.1.1 on 2018-10-19 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supply', models.CharField(max_length=20)),
                ('kefutelephone', models.CharField(max_length=20)),
            ],
        ),
    ]
